
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "externalsecret-phlp"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "secretstore-phlp-secret" #ref SecretStore object name
  target:
    name: "phlp-service1-secret"  #kubernetes secret to be created in namespace
  data:
    - secretKey: "username" #secret-key-to-be-managed in kubernetes
      remoteRef:
        key: "phlpsecret" #The aws secret manager name
        property: "username" #Key in Secrets Manager
    - secretKey: "password" #secret-key-to-be-managed in kubernetes
      remoteRef:
        key: "phlpsecret" 
        property: "password"
