image:
  repository: cgregistry.capgroup.com/external-secrets/external-secrets
 
#HA settings
replicaCount: 2
leaderElect: true
podDisruptionBudget:
  enabled: true
  minAvailable: 1

webhook:
  replicaCount: 2
  image:
    repository: cgregistry.capgroup.com/external-secrets/external-secrets
 
certController:
  replicaCount: 2
  image:
    repository: cgregistry.capgroup.com/external-secrets/external-secrets
